INSERT INTO `pidgeotour-destinos`.`destinos` (`id`, `valor`, `nome`, `descricao`, `duracao`, `pontos`) VALUES ('1', '150000.00', 'Kanto Red & Blue', 'descricao', '4 dias', 'pontos');
INSERT INTO `pidgeotour-destinos`.`destinos` (`id`, `valor`, `nome`, `descricao`, `duracao`, `pontos`) VALUES ('2', '175000.00', 'Kanto Ash Yellow', 'descricao', '4 dias', 'pontos');
INSERT INTO `pidgeotour-destinos`.`destinos` (`id`, `valor`, `nome`, `descricao`, `duracao`, `pontos`) VALUES ('3', '120000.00', 'Johto Gold & Silver', 'descricao', '3 dias', 'pontos');
INSERT INTO `pidgeotour-destinos`.`destinos` (`id`, `valor`, `nome`, `descricao`, `duracao`, `pontos`) VALUES ('4', '200000.00', 'Hoenn Ruby & Sapphire', 'descricao', '4 dias', 'pontos');
INSERT INTO `pidgeotour-destinos`.`destinos` (`id`, `valor`, `nome`, `descricao`, `duracao`, `pontos`) VALUES ('5', '205000.00', 'Sinnoh Diamond & Pearl', 'descricao', '4 dias', 'pontos');
INSERT INTO `pidgeotour-destinos`.`destinos` (`id`, `valor`, `nome`, `descricao`, `duracao`, `pontos`) VALUES ('6', '210000.00', 'Unova Black & White', 'descricao', '5 dias', 'pontos');
INSERT INTO `pidgeotour-destinos`.`destinos` (`id`, `valor`, `nome`, `descricao`, `duracao`, `pontos`) VALUES ('7', '210000.00', 'Kalos X & Y', 'descricao', '5 dias', 'pontos');
INSERT INTO `pidgeotour-destinos`.`destinos` (`id`, `valor`, `nome`, `descricao`, `duracao`, `pontos`) VALUES ('8', '210000.00', 'Alola Sun & Moon', 'descricao', '5 dias', 'pontos');
INSERT INTO `pidgeotour-destinos`.`destinos` (`id`, `valor`, `nome`, `descricao`, `duracao`, `pontos`) VALUES ('9', '225000.00', 'Galar Sword & Shield', 'descricao', '6 dias', 'pontos');
INSERT INTO `pidgeotour-destinos`.`destinos` (`id`, `valor`, `nome`, `descricao`, `duracao`, `pontos`) VALUES ('10', '220000.00', 'Paldea Scarlet & Violet', 'descricao', '6 dias', 'pontos');

INSERT INTO `pidgeotour-destinos`.`disponibilidade` (`id`, `nome`, `data`, `vagas`, `destino_id`) VALUES ('1', 'Kanto Red & Blue', '14/03/2023', '2', '1');
INSERT INTO `pidgeotour-destinos`.`disponibilidade` (`id`, `nome`, `data`, `vagas`, `destino_id`) VALUES ('2', 'Kanto Red & Blue', '21/03/2023', '5', '1');
INSERT INTO `pidgeotour-destinos`.`disponibilidade` (`id`, `nome`, `data`, `vagas`, `destino_id`) VALUES ('3', 'Kanto Red & Blue', '17/03/2023', '2', '1');
INSERT INTO `pidgeotour-destinos`.`disponibilidade` (`id`, `nome`, `data`, `vagas`, `destino_id`) VALUES ('4', 'Kanto Ash Yellow', '17/03/2023', '3', '2');
INSERT INTO `pidgeotour-destinos`.`disponibilidade` (`id`, `nome`, `data`, `vagas`, `destino_id`) VALUES ('5', 'Johto Gold & Silver', '17/03/2023', '4', '3');
INSERT INTO `pidgeotour-destinos`.`disponibilidade` (`id`, `nome`, `data`, `vagas`, `destino_id`) VALUES ('6', 'Hoenn Ruby & Sapphire', '21/03/2023', '7', '4');
INSERT INTO `pidgeotour-destinos`.`disponibilidade` (`id`, `nome`, `data`, `vagas`, `destino_id`) VALUES ('7', 'Johto Gold & Silver', '21/03/2023', '5', '3');
INSERT INTO `pidgeotour-destinos`.`disponibilidade` (`id`, `nome`, `data`, `vagas`, `destino_id`) VALUES ('8', 'Johto Gold & Silver', '24/03/2023', '7', '3');
INSERT INTO `pidgeotour-destinos`.`disponibilidade` (`id`, `nome`, `data`, `vagas`, `destino_id`) VALUES ('9', 'Unova Black & White', '21/03/2023', '4', '6');
INSERT INTO `pidgeotour-destinos`.`disponibilidade` (`id`, `nome`, `data`, `vagas`, `destino_id`) VALUES ('10', 'Kalos X & Y', '21/03/2023', '7', '7');
INSERT INTO `pidgeotour-destinos`.`disponibilidade` (`id`, `nome`, `data`, `vagas`, `destino_id`) VALUES ('11', 'Alola Sun & Moon', '21/03/2023', '2', '8');
INSERT INTO `pidgeotour-destinos`.`disponibilidade` (`id`, `nome`, `data`, `vagas`, `destino_id`) VALUES ('12', 'Alola Sun & Moon', '14/03/2023', '3', '8');
INSERT INTO `pidgeotour-destinos`.`disponibilidade` (`id`, `nome`, `data`, `vagas`, `destino_id`) VALUES ('13', 'Kalos X & Y', '14/03/2023', '7', '5');
INSERT INTO `pidgeotour-destinos`.`disponibilidade` (`id`, `nome`, `data`, `vagas`, `destino_id`) VALUES ('14', 'Unova Black & White', '14/03/2023', '7', '6');
INSERT INTO `pidgeotour-destinos`.`disponibilidade` (`id`, `nome`, `data`, `vagas`, `destino_id`) VALUES ('15', 'Sinnoh Diamond & Pearl', '14/03/2023', '6', '5');
INSERT INTO `pidgeotour-destinos`.`disponibilidade` (`id`, `nome`, `data`, `vagas`, `destino_id`) VALUES ('16', 'Hoenn Ruby & Sapphire', '14/03/2023', '3', '4');
INSERT INTO `pidgeotour-destinos`.`disponibilidade` (`id`, `nome`, `data`, `vagas`, `destino_id`) VALUES ('17', 'Kanto Red & Blue', '24/03/2023', '7', '1');
INSERT INTO `pidgeotour-destinos`.`disponibilidade` (`id`, `nome`, `data`, `vagas`, `destino_id`) VALUES ('18', 'Galar Sword & Shield', '24/03/2023', '5', '9');
INSERT INTO `pidgeotour-destinos`.`disponibilidade` (`id`, `nome`, `data`, `vagas`, `destino_id`) VALUES ('19', 'Galar Sword & Shield', '21/03/2023', '3', '9');
INSERT INTO `pidgeotour-destinos`.`disponibilidade` (`id`, `nome`, `data`, `vagas`, `destino_id`) VALUES ('20', 'Paldea Scarlet & Violet', '21/03/2023', '1', '10');